### ISSUE TITLE
File annotations

### ISSUE THREAD

**Issue by RWOverdijk** [congajs/conga-annotations#1]
I love this lib and would like to use it. I just have one question: Does it have file annotation support?

If at the top of your file, you place a docblock with annotations will it parse? Like this:

``` js
/**
 * @author RWOverdijk
 * @version 0.1.0
 */
```

**Comment by createvibe** [comment]
Sorry, this library doesn't support file level annotations.  Currently we support constructor, method, and property annotations.  I'm not really sure if it's within the scope of this library to parse DocBlock annotations like @author and @version on the file level.
