### ISSUE TITLE
CRLF vs LF

### ISSUE THREAD

**Issue by stefanbates** [congajs/conga-annotations#7]
Thanks for the parser. It's working perfectly for my needs except for one issue.

On Windows with JavaScript files containing line endings of CRLF the parser fails to find any annotations. If I change the line endings to LF it works fine.

**Comment by lampjunkie** [comment]
Hi Stefan,

Thanks for bringing this to my attention. I'm going to take a look to see if I can get this fixed!

**Comment by stefanbates** [comment]
Many thanks.

**Comment by lampjunkie** [comment]
Hi Stefan, this should work now.

Just make sure to install it via the new namespace that we recently moved it to (@conga/annotations) (v1.0.1) if you happen to have the older one installed.

https://www.npmjs.com/package/@conga/annotations

Enjoy, and please let me know if you come across any other issues!

**Comment by stefanbates** [comment]
Many thanks. That works great.
